### ISSUE TITLE
TODO:MapsAPI

### ISSUE THREAD

**Issue by ChristopherRoy1** [ChristopherRoy1/noSlip#1]
## MAPS API
- [x] Get API Key
- [ ] Connecting a pin to the map
- [ ] Getting distance between location and pin
- [ ] Get current location
